# Generated by Django 5.1 on 2024-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=900)),
                ('item_desc', models.CharField(max_length=90000)),
                ('item_type', models.CharField(max_length=9000)),
                ('item_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
