# Generated by Django 5.1 on 2024-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0002_remove_item_item_type_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(default='0'),
        ),
    ]
