# Generated by Django 5.1 on 2024-10-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_id_laptop_laptop_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
